const axios = require("axios");

// PARALLEL TEST-ONLY provider. Does not replace API-King (see apiKingService.js) —
// this exists purely so IMB's OTP endpoints can be exercised via imbOtpTest.js
// before any real login/signup flow is switched over.
const BASE_URL = "https://secure.imbpayment.in/api/v1";

function imbHeaders() {
  const clientId = process.env.IMB_CLIENT_ID;
  const clientSecret = process.env.IMB_CLIENT_SECRET;
  if (!clientId || !clientSecret) throw new Error("IMB_CLIENT_ID / IMB_CLIENT_SECRET not set");
  return {
    "x-client-id": clientId,
    "x-client-secret": clientSecret,
    "Content-Type": "application/json",
  };
}

// Sends a caller-generated OTP over SMS via IMB.
async function sendMobileOtp(mobileNumber, otpCode) {
  let res;
  try {
    res = await axios.post(
      `${BASE_URL}/comunication/send-sms`,
      { mobile_number: mobileNumber, otp_code: otpCode },
      { headers: imbHeaders(), timeout: 8000 }
    );
  } catch (e) {
    if (e.code === "ECONNABORTED") throw new Error("IMB send-sms request timed out");
    const detail = e.response?.data ? JSON.stringify(e.response.data) : e.message;
    throw new Error(`IMB send-sms failed: ${detail}`);
  }

  const body = res.data || {};
  const failed = body.success === false || body.status === false ||
    (typeof body.status === "string" && /error|fail/i.test(body.status));
  if (failed) throw new Error("IMB send-sms failed: " + JSON.stringify(body));

  return body;
}

// Asks IMB to generate and send an Aadhaar OTP. Returns the request_id needed
// to verify it — unlike sendMobileOtp, the OTP itself is generated by IMB.
async function sendAadhaarOtp(aadhaarNumber) {
  let res;
  try {
    res = await axios.post(
      `${BASE_URL}/aadhaar/send-otp`,
      { aadhaar_number: aadhaarNumber },
      { headers: imbHeaders(), timeout: 8000 }
    );
  } catch (e) {
    if (e.code === "ECONNABORTED") throw new Error("IMB aadhaar/send-otp request timed out");
    const detail = e.response?.data ? JSON.stringify(e.response.data) : e.message;
    throw new Error(`IMB aadhaar/send-otp failed: ${detail}`);
  }

  const body = res.data || {};
  const failed = body.success === false || body.status === false ||
    (typeof body.status === "string" && /error|fail/i.test(body.status));
  if (failed) throw new Error("IMB aadhaar/send-otp failed: " + JSON.stringify(body));

  const requestId = body.request_id || body.data?.request_id || body.result?.request_id || null;
  return { request_id: requestId, raw: body };
}

// Verifies an Aadhaar OTP against the request_id from sendAadhaarOtp.
// NOTE: the exact body shape wasn't documented — { request_id, otp } is a
// reasonable guess and should be confirmed against IMB's real response once
// send-otp is tested against their sandbox/live API.
async function verifyAadhaarOtp(requestId, otp) {
  let res;
  try {
    res = await axios.post(
      `${BASE_URL}/aadhaar/verify-otp`,
      { request_id: requestId, otp },
      { headers: imbHeaders(), timeout: 8000 }
    );
  } catch (e) {
    if (e.code === "ECONNABORTED") throw new Error("IMB aadhaar/verify-otp request timed out");
    const detail = e.response?.data ? JSON.stringify(e.response.data) : e.message;
    throw new Error(`IMB aadhaar/verify-otp failed: ${detail}`);
  }

  const body = res.data || {};
  const failed = body.success === false || body.status === false ||
    (typeof body.status === "string" && /error|fail/i.test(body.status));
  if (failed) throw new Error("IMB aadhaar/verify-otp failed: " + JSON.stringify(body));

  return body;
}

module.exports = { sendMobileOtp, sendAadhaarOtp, verifyAadhaarOtp };
